"""adds new fields for collect UI

Revision ID: 46ba9a510ec3
Revises: d6c73e520170
Create Date: 2022-06-14 22:54:24.922933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46ba9a510ec3'
down_revision = 'd6c73e520170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attribute', sa.Column('label', sa.String(length=255), nullable=False))
    op.add_column('attribute', sa.Column('isMulti', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characteristic', 'id')
    op.drop_column('attribute', 'isMulti')
    op.drop_column('attribute', 'label')
    # ### end Alembic commands ###
