"""removes id

Revision ID: d6c73e520170
Revises: 
Create Date: 2022-06-09 15:24:12.888631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c73e520170'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association', sa.Column('subcategory_id', sa.Integer(), nullable=False))
    op.add_column('association', sa.Column('attribute_id', sa.Integer(), nullable=False))
    op.drop_column('association', 'id')
    op.drop_column('characteristic', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('association', 'attribute_id')
    op.drop_column('association', 'subcategory_id')
    # ### end Alembic commands ###
